name: "Test Workflow"
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }} 
      - run: echo ${{ github.event.ref }} 
      - run: echo ${{ github.event.ref_type }} 
      - run: echo ${{ github.event.sha }} 
      - run: env | grep GITHUB_ | sort
      - run: echo ${GITHUB_SHA} 
